"""add legendary columns

Revision ID: 655252f63799
Revises: 
Create Date: 2026-01-02 00:40:54.231191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655252f63799'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_legendary', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('player_slug', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tournament', sa.String(length=255), nullable=True))
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_products_player_slug'), ['player_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_player_slug'))
        batch_op.alter_column('club_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tournament')
        batch_op.drop_column('player_slug')
        batch_op.drop_column('is_legendary')

    # ### end Alembic commands ###
