"""add_chatbot_memory_fields_to_user

Revision ID: d460f9ca15c3
Revises: 655252f63799
Create Date: 2026-01-07 21:56:17.458824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd460f9ca15c3'
down_revision = '655252f63799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurements', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('preferences')
        batch_op.drop_column('measurements')

    # ### end Alembic commands ###
